name: CI

on:
  push:
    branches: [main, feat-reports-page]
  pull_request:
    branches: '**'

jobs:
  build:
    name: 'Build ğŸ§±'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Install pnpm
        run: npm install -g pnpm # Installs pnpm globally

      - name: Confirm pnpm installation
        run: pnpm --version # Verifies that pnpm is installed and in PATH

      - name: Install dependencies
        run: pnpm install # Installs project dependencies

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0
          cache: 'pnpm'

      - name: Build project
        run: pnpm run build # Builds your project

      - name: Build Application ğŸ§±
        run: pnpm run build
        env:
          NEXT_PUBLIC_API_URL: https://api.example.com

  lint:
    name: 'Lint ğŸ±'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Lint JS files ğŸ±
        run: pnpm run lint:js

      - name: Lint CSS files ğŸ±
        run: pnpm run lint:css
